### PR TITLE
Added set schedule + anti crash

### PR DESCRIPTION
**Pull request by pvgennip**
Added schedule setting to the maxcube factory and class by array of times and temperatures per weekday. Added battery_low and panel_locked to the standard deviceInfo.

At timeout of a connection to a cube, Node crashed, because there was no event handler for ETIMEDOUT and other events caused by unstable connection. Prevented crashing by adding a process handler for uncaughtException.

### CODE REVIEW

**Comment by normen** [comment]
Hi, I started work on a "maxcube2" library here in case you're interested, I integrated your PR:
https://github.com/normen/maxcube2

**Comment by ivesdebruycker** [comment]
@pvgennip , thanks for your great work!

**Comment by pvgennip** [comment]
@ivesdebruycker: you too!

Kind regards,
Pim van Gennip
iconize.nl

On 6 March 2018 at 22:31:28, ivesdebruycker (notifications@github.com) wrote:

@pvgennip , thanks for your great work!

**Pull request merged**
